# Config file for automatic testing at travis-ci.org
language: python

matrix:
    include:
        - python: 2.7
          env: KERAS_BACKEND=theano
        - python: 3.5
          env: KERAS_BACKEND=theano

notifications:
  email: true

install:
  #code below copied from keras' .travis.yml
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pytest h5py nose
  - source activate test-environment
  - pip install theano
  - pip install keras==1.2

script:
- PYTHONPATH=$PWD:$PYTHONPATH py.test
